language: node_js
node_js:
  - "9"
  - "8"
cache:
  timeout: 600
  directories:
    - node_modules
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist
    on:
      branch: master
  - provider: releases
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    file_glob: true
    file: 'dist/*'
    on:
      branch: master
      tags: true